# Generated by Django 5.2.7 on 2025-11-07 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assigned_to',
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='image',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='status',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='issue',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='ai_detected_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='issue_photos/'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('Road Damage', 'Road Damage'), ('Garbage Collection', 'Garbage Collection'), ('Electrical Issue', 'Electrical Issue'), ('Water Supply', 'Water Supply'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
