# Generated by Django 5.2.7 on 2025-11-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_issue_options_remove_issue_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('infrastructure', 'Infrastructure — Roads, bridges, sidewalks, public buildings'), ('sanitation', 'Sanitation — Garbage collection, waste management, cleanliness'), ('public_safety', 'Public Safety — Street lighting, traffic signals, security concerns'), ('utilities', 'Utilities — Water supply, electricity, gas, telecommunications'), ('transportation', 'Transportation — Public transit, parking, traffic management'), ('environment', 'Environment — Parks, trees, pollution, noise complaints')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='severity',
            field=models.CharField(choices=[('minor', 'Minor'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=50),
        ),
    ]
